language: c

compiler:
  - clang
  - gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y libfuse-dev
    - curl -LO https://github.com/jedisct1/libsodium/releases/download/1.0.0/libsodium-1.0.0.tar.gz
    - tar -xzf libsodium-1.0.0.tar.gz
    - cd libsodium-1.0.0 && ./configure --prefix=/usr && make && sudo make install

pre_script:
    - mkdir -p build

script:
    - cd build && cmake .. && make && make test
